// 五大劫：18 高考(QTE) / 22 求职 / 28 相亲 / 35 裁员 / 66 病床
window.BH = window.BH || {};
BH.BOSSES = [
  { age: 18, id: 'gaokao', name: '高考', type: 'qte', clickK: 0.5,
    base: { INT: 2.2, STR: 0.3 },
    talBonus: { xueshen: { add: 6 }, dushu: { add: 3 }, gaojia: { add: 3 }, yeli: { add: 2 }, shimian: { add: 2 }, tanwan: { add: -2 } },
    traitBonus: { zaoba2: 2, kaogong: 2, duliu: 2 },
    t: '★ 大劫·高考。教室里的笔尖声像一场大雨。' ,
    desc: '5 秒内狂点答题！你的属性和天赋会替你压阵。',
    opts: [
      { id: 'ben', min: 26, rt: '你上了一本线，全家在小区门口放了挂鞭。', e: { JOY: 2 }, f: 'univ', tg: ['study'] },
      { id: 'da', min: 15, rt: '你上了大专，但大专里藏着另一种人生。', e: { JOY: 1 }, f: 'univ2', tg: ['study'] },
      { id: 'luo', min: -999, rt: '你落榜了，复读、进厂、社会大学，路不止一条。', e: { JOY: -1, MNY: -1 }, f: 'gaokao_fail', tg: ['chaos'] },
    ] },
  { age: 22, id: 'qiuzhi', name: '求职', type: 'show',
    base: { INT: 1.5, CHR: 1.2, MNY: 0.3 },
    talBonus: { tieshen: { add: 4 }, yinyang_trait: { add: 0 }, meimao: { add: 3 }, dazhuang: { add: 2 } },
    traitBonus: { yinyang: 4, huabing: 2, yuanjia: 2, wanneng: 1 },
    trackBonus: { dianjing: 2 },
    t: '★ 大劫·求职。面试官的微笑深不可测，你的简历薄得像秋天的叶子。',
    desc: '你的全部积累将逐项拍入。',
    opts: [
      { id: 'big', min: 24, rt: '你拿到了大厂 offer，工牌挂上的那一刻，你给家里打了电话。', e: { MNY: 3, JOY: 1 }, f: 'job_big', tg: ['study'] },
      { id: 'mid', min: 12, rt: '你进了一家小公司，钱少事多，但同事都是好人。', e: { MNY: 1 }, f: 'job_mid' },
      { id: 'none', min: -999, rt: '你暂时待业，在家考公/啃老/搞副业，三条路都是路。', e: { MNY: -1, JOY: -1 }, f: 'job_none', tg: ['chaos'] },
    ] },
  { age: 28, id: 'xiangqin', name: '相亲', type: 'show',
    base: { CHR: 1.5, MNY: 1.0, JOY: 0.5 },
    talBonus: { meimao: { add: 4 }, chunai: { add: 3 }, fengkuang: { add: 3 }, shekong: { add: -3 } },
    traitBonus: { lianai: 4, yinyang: -2, jianmei: 2 },
    trackBonus: {},
    t: '★ 大劫·相亲。咖啡厅的背景音乐是爵士，对面的人在看手机。',
    desc: '魅力、家境与真诚的加权总决算。',
    opts: [
      { id: 'yes', min: 20, rt: '对上了，你们在第二家咖啡厅聊到了打烊。', e: { JOY: 3, CHR: 1 }, f: 'married_soon', tg: ['love'] },
      { id: 'next', min: 8, rt: '加了微信，聊了三天，互相发了"在忙"，然后就是永远的在忙。', e: { JOY: -1 }, tg: ['love'] },
      { id: 'no', min: -999, rt: '你决定再等等，等一个不用相亲就能对上眼的人。', e: { JOY: 1 }, tg: ['lie'] },
    ] },
  { age: 35, id: 'caiyuan', name: '35 岁危机', type: 'show',
    base: { MNY: 1.2, INT: 1.0, STR: 0.5 },
    talBonus: { xueshen: { add: 2 }, fengkuang: { add: 4 } },
    traitBonus: { huabing: 3, wanneng: 2, moyu: 2, shouc: 1 },
    trackBonus: { fuhao: 3, dianjing: 2 },
    t: '★ 大劫·35 岁。优化名单的传闻在茶水间飞了一周，你假装没听见。',
    desc: '你的不可替代性，现在结账。',
    opts: [
      { id: 'up', min: 26, rt: '你晋升了，名单上的名字是别人的，你在电梯里松了一口气。', e: { MNY: 3, JOY: 1 }, f: 'survive35', tg: ['study'] },
      { id: 'side', min: 14, rt: '你还是被优化了，但副业接住了你，你笑着签了字。', e: { MNY: 1, JOY: 1 }, f: 'side_rescue', tg: ['chaos'] },
      { id: 'down', min: -999, rt: '你被优化了，N+1 到账，你在家躺了一周，然后开始投简历。', e: { MNY: 1, JOY: -2 }, f: 'laidoff', tg: ['chaos'] },
    ] },
  { age: 66, id: 'bingchuang', name: '病床大劫', type: 'show',
    base: { STR: 2.0, MNY: 1.0, JOY: 0.8 },
    talBonus: { tieshen: { add: 4 }, laodang: { add: 4 }, yisui: { add: -4 } },
    traitBonus: { pao: 3, shuimian: 2, ganfan: 2, zaoqi: 2 },
    trackBonus: { xiuxian: 4 },
    t: '★ 大劫·病床。白炽灯很亮，护工的拖鞋声在走廊里来回。',
    desc: '身体的底子，现在见分晓。',
    opts: [
      { id: 'fine', min: 22, rt: '你安然度过，医生说你的血管像五十岁的，你笑纳了。', e: { JOY: 2, LIF: 3 }, tg: ['family'] },
      { id: 'slow', min: 10, rt: '你留了几天院，出院时拄了根拐，从此它成了你的第三条腿。', e: { STR: -1 }, tg: ['family'] },
      { id: 'hard', min: -999, rt: '这场病带走了你一部分的力气，也带走了你的舍不得——你开始认真安排后事了。', e: { STR: -2, JOY: -1 }, tg: ['chaos'] },
    ] },
];
