// 五大劫：18 高考(QTE) / 22 求职 / 28 相亲 / 35 裁员 / 66 病床
// v2：三幕化——rt 扩为多句现场文本，opts 写结果旗标供后幕剧本续演（20-arcs.md §3）
window.BH = window.BH || {};
BH.BOSSES = [
  { age: 18, id: 'gaokao', name: '高考', type: 'qte', clickK: 0.5,
    base: { INT: 2.2, STR: 0.3 },
    talBonus: { xueshen: { add: 6 }, dushu: { add: 3 }, gaojia: { add: 3 }, yeli: { add: 2 }, shimian: { add: 2 }, tanwan: { add: -2 }, zhutou: { add: -1 } },
    traitBonus: { zaoba2: 2, kaogong: 2, duliu: 2 },
    t: '★ 大劫·高考。教室里的笔尖声像一场大雨，你在这场雨里站了三年。',
    desc: '5 秒内狂点答题！你的属性和天赋会替你压阵。',
    opts: [
      { id: 'ben', min: 26, rt: '交卷铃响的那一刻你反而平静了。出分那晚全家把手机递来递去看了十遍——你过了一本线，小区门口的鞭炮是你爸放的，他坚持说是邻居放的。', e: { JOY: 2 }, f: 'univ', tg: ['study'] },
      { id: 'da', min: 15, rt: '成绩不算体面，但你妈只说了一句"学校有床吗，给你装点牛奶"。大专录取通知到的那天，你把"大专也是大学"设成了签名。', e: { JOY: 1 }, f: 'univ2', tg: ['study'] },
      { id: 'luo', min: -999, rt: '出分那晚你把手机扣在桌上，全家谁也没说话。复读、进厂、闯社会——路不止一条，但今晚你只想先睡一觉，明天再说。', e: { JOY: -1, MNY: -1 }, f: 'gaokao_fail', tg: ['chaos'] },
    ] },
  { age: 22, id: 'qiuzhi', name: '求职', type: 'show',
    base: { INT: 1.5, CHR: 1.2, MNY: 0.3 },
    talBonus: { tieshen: { add: 4 }, meimao: { add: 3 }, dazhuang: { add: 2 } },
    traitBonus: { yinyang: 4, huabing: 2, yuanjia: 2, wanneng: 1 },
    trackBonus: { dianjing: 2 },
    t: '★ 大劫·求职。面试官的微笑深不可测，你的简历薄得像秋天的叶子。',
    desc: '你的全部积累将逐项拍入。',
    opts: [
      { id: 'big', min: 24, rt: 'offer 邮件是下午三点到的，你先给家里打了电话，第一句是"妈，我工作了"，第二句没说出来。工牌挂上的那一刻，你对着电梯镜子里的人看了很久。', e: { MNY: 3, JOY: 1 }, f: 'job_big', tg: ['study'] },
      { id: 'mid', min: 12, rt: '小公司，钱少事多，好在离家近、人真实。老板偶尔画饼，但饼是素的，你能吃得下。入职第一天你把工位擦了三遍。', e: { MNY: 1 }, f: 'job_mid' },
      { id: 'none', min: -999, rt: '毕业即待业。白天投简历，下午学做饭，晚上安慰自己这叫 gap。爸妈的沉默是一种笨拙的宽容，你听懂了。', e: { MNY: -1, JOY: -1 }, f: 'job_none', tg: ['chaos'] },
    ] },
  { age: 28, id: 'xiangqin', name: '相亲', type: 'show',
    base: { CHR: 1.5, MNY: 1.0, JOY: 0.5 },
    talBonus: { meimao: { add: 4 }, chunai: { add: 3 }, fengkuang: { add: 3 }, shekong: { add: -3 } },
    traitBonus: { lianai: 4, yinyang: -2, jianmei: 2 },
    trackBonus: {},
    t: '★ 大劫·相亲。咖啡厅的背景音乐是爵士，对面的人放下手机冲你笑了笑。',
    desc: '魅力、家境与真诚的加权总决算。',
    opts: [
      { id: 'yes', min: 20, rt: '对方第二次约你时，你居然有点期待。第二家咖啡厅你们聊到打烊，服务员擦了三次桌子，最后一次是赶你们走的。', e: { JOY: 3, CHR: 1 }, f: 'married_soon', tg: ['love'] },
      { id: 'next', min: 8, rt: '加了微信，聊了三天，最后一条消息停在"在忙"。你给这次相亲的备注是：不讨厌，也不心动，像一杯温水。', e: { JOY: -1 }, tg: ['love'] },
      { id: 'no', min: -999, rt: '你跟介绍人说"再等等"。回家路上你给自己点了份炸鸡，自由的味道，有点咸。', e: { JOY: 1 }, tg: ['lie'] },
    ] },
  { age: 35, id: 'caiyuan', name: '35 岁危机', type: 'show',
    base: { MNY: 1.2, INT: 1.0, STR: 0.5 },
    talBonus: { xueshen: { add: 2 }, fengkuang: { add: 4 } },
    traitBonus: { huabing: 3, wanneng: 2, moyu: 2, shouc: 1 },
    trackBonus: { fuhao: 3, dianjing: 2 },
    t: '★ 大劫·35 岁。优化名单的传闻在茶水间飞了一周，你的工牌突然变得很沉。',
    desc: '你的不可替代性，现在结账。',
    opts: [
      { id: 'up', min: 26, rt: '名单公布，你的名字不在上面，还在晋升名单的第一页。电梯里你松了一口气，然后发现自己在笑，笑得像刚毕业那年。', e: { MNY: 3, JOY: 1 }, f: 'survive35', tg: ['study'] },
      { id: 'side', min: 14, rt: '你还是被优化了。签字那天你没慌——副业账户的余额替你撑住了腰。HR 说"祝你前程似锦"，你说"会的"，这次是真心的。', e: { MNY: 1, JOY: 1 }, f: 'side_rescue', tg: ['chaos'] },
      { id: 'down', min: -999, rt: 'N+1 到账那天，你在家里躺了三天。第三天下午你收拾了书桌，改了简历的开头一句。日子还在，人也还在。', e: { MNY: 1, JOY: -2 }, f: 'laidoff', tg: ['chaos'] },
    ] },
  { age: 66, id: 'bingchuang', name: '病床大劫', type: 'show',
    base: { STR: 2.0, MNY: 1.0, JOY: 0.8 },
    talBonus: { tieshen: { add: 4 }, laodang: { add: 4 }, yisui: { add: -4 } },
    traitBonus: { pao: 3, shuimian: 2, ganfan: 2, zaoqi: 2 },
    trackBonus: { xiuxian: 4 },
    t: '★ 大劫·病床。白炽灯很亮，护工的拖鞋声在走廊里来来回回。',
    desc: '身体的底子，现在见分晓。',
    opts: [
      { id: 'fine', min: 22, rt: '复查结果出来，医生把报告推给你："血管像五十岁的。"你笑纳了这句夸奖，出院那天你走楼梯下的楼，一层一层，稳稳的。', e: { JOY: 2, LIF: 3 }, f: 'bc_fine', tg: ['family'] },
      { id: 'slow', min: 10, rt: '你住了半个月院，出院时多了根拐杖。头几天它硌手，后来它成了你的第三条腿，你们相处得还不错。', e: { STR: -1 }, f: 'bc_slow', tg: ['family'] },
      { id: 'hard', min: -999, rt: '这场病带走了一部分力气。你坐在病床上把存折、密码和遗愿一样一样理清楚——不是认输，是想把剩下的事办得体面。', e: { STR: -2, JOY: -1 }, f: 'bc_hard', tg: ['chaos'] },
    ] },
];
