// 死法图鉴：意外池（每条 = 一张图鉴卡）
window.BH = window.BH || {};
BH.DEATHS = [
  { t: '你在阳台给多肉浇水时脚下一滑，人和多肉一起完成了最后一次光合作用。', death: { cause: '阳台失足', icon: '🪴' }, ironyTags: [] },
  { t: '你被广场舞的音响电流击中，邻居们说你是笑着走的。', death: { cause: '音响漏电', icon: '🕺' }, ironyTags: ['fame'] },
  { t: '你在试吃免费试吃品时被噎住，店员已读乱回，错过了黄金时间。', death: { cause: '试吃噎住', icon: '🥟' }, ironyTags: [] },
  { t: '你为了抢演唱会门票的手速挑战，激动过度，心脏罢工了。', death: { cause: '抢票猝死', icon: '🎫' }, ironyTags: ['fame'] },
  { t: '你在熬夜赶方案时永远地睡着了，方案过了，你没过。', death: { cause: '过劳猝死', icon: '💻' }, ironyTags: ['chaos'] },
  { t: '你在家烤蛋糕，烤箱和你一起退役了，起火原因不明。', death: { cause: '烤箱起火', icon: '🔥' }, ironyTags: [] },
  { t: '你淋雨跑完五公里后洗了个热水澡，生命在蒸汽里升华了。', death: { cause: '淋雨洗浴', icon: '🚿' }, ironyTags: [] },
  { t: '你和杠精对线三天三夜，赢了争论，输了血压。', death: { cause: '气到升天', icon: '💬' }, ironyTags: ['chaos'] },
  { t: '你在钓鱼时把鱼竿甩到了高压线上，鱼没钓到，你先上岸了。', death: { cause: '钓鱼触电', icon: '🎣' }, ironyTags: ['diaoyu'] },
  { t: '你在小区里追一只猫，追进了没有井盖的下水道。', death: { cause: '追猫失误', icon: '🐈' }, ironyTags: [] },
  { t: '你沉迷抽象直播，连续刷礼物刷到手机发烫，你比手机先热过头。', death: { cause: '直播间猝死', icon: '📱' }, ironyTags: ['fame'] },
  { t: '你吃完三斤小龙虾后喝了冰可乐，肠胃举行了罢工大会并宣判了你的命运。', death: { cause: '吃虾风暴', icon: '🦞' }, ironyTags: [] },
  { t: '你在给娃辅导作业时血条清零，据邻居描述，你最后喊的是"这题讲过八遍了"。', death: { cause: '辅导作业', icon: '📐' }, ironyTags: ['family'] },
  { t: '你在浴室唱歌，唱到了最高音，镜子碎了，你也碎了。', death: { cause: '高音震碎', icon: '🎤' }, ironyTags: ['art'] },
  { t: '你骑着共享单车逆行，和对面的电动车完成了一次物理学实验。', death: { cause: '逆行相撞', icon: '🚲' }, ironyTags: [] },
  { t: '你给手机边充边玩，手机没炸，插座先表态了。', death: { cause: '边充边玩', icon: '🔌' }, ironyTags: ['chaos'] },
  { t: '你徒步进山没看天气预报，山里的雨比你的求生欲来得快。', death: { cause: '徒步遇雨', icon: '⛰️' }, ironyTags: [] },
  { t: '你在网购节连抢七天，第八天你没醒，购物车满了，人空了。', death: { cause: '双十一猝死', icon: '🛒' }, ironyTags: ['rich'] },
  { t: '你健身时挑战了超过自身极限的重量，器械见证了你的勇气。', death: { cause: '健身事故', icon: '🏋️' }, ironyTags: [] },
  { t: '你在麻将桌上自摸了天胡，笑得比胡得快，先走了一步。', death: { cause: '天胡驾鹤', icon: '🀄' }, ironyTags: [] },
  { t: '你在阳台抽烟，烟头点燃了楼下晾晒的棉被，你扑火的方式过于勇猛。', death: { cause: '阳台救火', icon: '🚒' }, ironyTags: [] },
  { t: '你吃了隔夜的王水菠菜？不，是放了三天的剩饭，细菌先动的手。', death: { cause: '剩饭中毒', icon: '🍚' }, ironyTags: [] },
  { t: '你在水里展示了新学的泳姿，展示到一半，泳池收回了你的使用权。', death: { cause: '泳姿失控', icon: '🏊' }, ironyTags: [] },
  { t: '你在动物园投喂猴子，猴子的回应超出你的处理能力。', death: { cause: '猴哥出手', icon: '🐒' }, ironyTags: [] },
  { t: '你顶着 40 度高温搬家，家具安全入户，你留在了楼道。', death: { cause: '高温搬家', icon: '📦' }, ironyTags: [] },
  { t: '你在网吧连坐三天，屏幕上的战绩辉煌，椅子上的人安静。', death: { cause: '网吧久坐', icon: '🖥️' }, ironyTags: ['dianjing'] },
  { t: '你为给偶像打投连熬三夜，你的哥哥出道了，你下播了。', death: { cause: '打投过劳', icon: '🌟' }, ironyTags: ['fame'] },
  { t: '你自制的"健身餐"里误放了过期的蛋白粉，蛋白没补上，你先粉身碎骨。', death: { cause: '过期蛋白粉', icon: '🥛' }, ironyTags: [] },
  { t: '你在婚纱照外景拍摄时爬上了网红礁石，海浪比你的婚纱先到。', death: { cause: '网红礁石', icon: '🌊' }, ironyTags: ['love'] },
  { t: '你在公司年会上表演了一个太卖力的节目，主打一个"一个都不留"。', death: { cause: '年会事故', icon: '🎪' }, ironyTags: [] },
  { t: '你沉迷刷短视频"再看一个就睡"，一千个"再一个"之后，你真的睡了。', death: { cause: '短视频长眠', icon: '📼' }, ironyTags: [] },
  { t: '你骑摩托车压弯压出了物理学新结论，交警来晚了一步。', death: { cause: '压弯失控', icon: '🏍️' }, ironyTags: [] },
  { t: '你在冰面行走展示自信，冰面展示了它的极限。', death: { cause: '冰面事故', icon: '🧊' }, ironyTags: [] },
  { t: '你熬夜看球，绝杀球进了，你却没能看到回放。', death: { cause: '看球猝死', icon: '⚽' }, ironyTags: [] },
  { t: '你给全楼修 WiFi 修出了口碑，最后一单是你家的老插座。', death: { cause: '维修触电', icon: '🛠️' }, ironyTags: [] },
  { t: '你在婚宴上喝多了，敬酒敬到第三十桌，坚持完成了仪式，倒在了收礼金前。', death: { cause: '婚宴过量', icon: '🍻' }, ironyTags: ['love'] },
  { t: '你挤早高峰地铁挤出了阑尾炎，忍到公司才发作，公司表扬你敬业（不是）。', death: { cause: '地铁延误', icon: '🚇' }, ironyTags: [] },
  { t: '你在露营地用卡式炉煮火锅，卡式炉和帐篷对你的操作很有意见。', death: { cause: '露营事故', icon: '⛺' }, ironyTags: [] },
  { t: '你网购的"网红减肥药"效果显著，三天瘦了十八斤，第四天没称上。', death: { cause: '三无减肥药', icon: '💊' }, ironyTags: ['chaos'] },
  { t: '你玩密室逃脱卡关两小时，触发机关时的位置太刁钻，NPC 都救不了你。', death: { cause: '密室事故', icon: '🔒' }, ironyTags: ['guaitan'] },
  { t: '你横穿马路抢了两秒，你的整个人生停在了一根斑马线前。', death: { cause: '横穿马路', icon: '🚥' }, ironyTags: [] },
  { t: '你家养的鹦鹉学会了"救火！救火！"，那天它是真的在喊。', death: { cause: '家中失火', icon: '🦜' }, ironyTags: [] },
  { t: '你在暴雨天涉水推车，车没推出去，你被水流带走了，雨刷器还在动。', death: { cause: '暴雨涉水', icon: '🌧️' }, ironyTags: [] },
  { t: '你在游乐园排队三小时，过山车第一个下坡你就理解了什么叫"人生走马灯"。', death: { cause: '过山车惊魂', icon: '🎢' }, ironyTags: [] },
  { t: '你给公司年会的抽奖箱通了电，想搞个"刺激的"，确实很刺激。', death: { cause: '年会整活', icon: '🎁' }, ironyTags: ['chaos'] },
  { t: '你在老家柴火灶前打盹，火星子替你完成了人生最后一次炊烟。', death: { cause: '柴火灶失火', icon: '🔥' }, ironyTags: [] },
  { t: '你长时间低头玩手机，颈椎举行了无声的抗议，抗议方式是彻底罢工。', death: { cause: '颈椎罢工', icon: '📱' }, ironyTags: [] },
  { t: '你在拍卖会上举到了最后一块牌子，那块地是你的了，激动的心跳停在了竞价槌落下之前。', death: { cause: '拍卖猝死', icon: '🔨' }, ironyTags: ['rich'] },
  { t: '你参加吃辣挑战，第九根死神辣椒后，你的舌头和心脏同时认输。', death: { cause: '辣王驾崩', icon: '🌶️' }, ironyTags: [] },
  { t: '你家里的老插线板勤勤恳恳服务十年，最后带着全套电器与你告别。', death: { cause: '插线板殉职', icon: '⚡' }, ironyTags: [] },
  { t: '你在雪乡旅游非要在栈道外拍照，雪很软，地面很硬。', death: { cause: '雪地拍照', icon: '🏔️' }, ironyTags: [] },
  { t: '你和朋友比拼"谁能憋气更久"，比赛地点选在了浴缸，你们的友谊和呼吸一起结束了。', death: { cause: '憋气比赛', icon: '🛁' }, ironyTags: ['chaos'] },
  { t: '你网购的巨型盲盒卡在楼梯间，你去推，它去滚，物理选择了它。', death: { cause: '盲盒压顶', icon: '📦' }, ironyTags: ['ergci'] },
  { t: '你驱车十小时去看海，到了海边太兴奋，游过了安全线，海收下了你。', death: { cause: '野海游泳', icon: '🏖️' }, ironyTags: [] },
  { t: '你在阳台给流浪猫搭窝，搭到一半，你比猫先住进了那个纸箱。', death: { cause: '搭窝失误', icon: '📦' }, ironyTags: [] },
  { t: '你自称"酒神"，在酒桌上立了 flag，flag 立得快，倒得更快。', death: { cause: '酒桌flag', icon: '🍺' }, ironyTags: ['chaos'] },
  { t: '你相信了"生水泡柠檬更养生"，柠檬是无辜的，你也是，学理科的邻居哭晕在厕所。', death: { cause: '生水养生', icon: '🍋' }, ironyTags: [] },
  { t: '你在台风天出门买奶茶，奶茶买到了，你和奶茶都没能回家。', death: { cause: '台风天买奶茶', icon: '🧋' }, ironyTags: [] },
  { t: '你在婚礼上接到了捧花，激动转身时踩到了自己的裙摆，从舞台滚下的姿势十分壮观。', death: { cause: '捧花滚落', icon: '💐' }, ironyTags: ['love'] },
  { t: '你买了台跑步机，它成了你家最高级的晾衣架，某晚它连着衣服一起倒了。', death: { cause: '跑步机压顶', icon: '🏃' }, ironyTags: [] },
  { t: '你沉迷"电子木鱼"，敲了三天三夜攒功德，功德没攒满，人先满了。', death: { cause: '电子木鱼功德圆满', icon: '🪷' }, ironyTags: ['weird'] },
  { t: '你给整栋楼的热心肠们表演"阳台墙外取快递"，物业提词器没跟上你的勇气。', death: { cause: '取快递坠楼', icon: '📦' }, ironyTags: [] },
  { t: '你熬夜追完大结局，编剧埋的雷在最后一集炸了，你的血压也炸了。', death: { cause: '追剧血压', icon: '📺' }, ironyTags: ['chaos'] },
  { t: '你在自家阳台对着夜空练习无实物脱口秀，惊醒了整栋楼的狗，狗们的反应超出了你的预期。', death: { cause: '阳台呐喊', icon: '📣' }, ironyTags: ['chaos'] },
  { t: '你在野温泉泡到一半，温泉水突然退了，你才想起这里是火山地质带。', death: { cause: '野温泉', icon: '♨️' }, ironyTags: [] },
  { t: '你参加公司团建的"信任背摔"，同事们移动得比你的信念快。', death: { cause: '团建事故', icon: '🤝' }, ironyTags: [] },
  { t: '你熬过了三年之痒、七年之痒，没能熬过物业通知的"外墙脱落"。', death: { cause: '外墙脱落', icon: '🧱' }, ironyTags: ['family'] },
  { t: '你收集的手办墙高达两米，地震没有来，猫来了。', death: { cause: '手办墙倒塌', icon: '🗿' }, ironyTags: ['ergci'] },
  { t: '你钓上来一条四十斤的大鱼，合影、发圈、举起——你的心血管选择了在巅峰退役。', death: { cause: '巨鱼合影', icon: '🐟' }, ironyTags: ['diaoyu'] },
  { t: '你在演唱会荧光海里蹦得最高，落下来的时候没人接住你。', death: { cause: '演唱会蹦跳', icon: '🎤' }, ironyTags: ['fame'] },
  { t: '你买了台二手电热毯，型号停产十年，它在某个寒夜里完成了最后的使命。', death: { cause: '二手电热毯', icon: '🛏️' }, ironyTags: [] },
  { t: '你在游乐园玩套圈，套中了十米外的大鹅，追逐大鹅的过程中，你体验到了极限心率。', death: { cause: '套圈大鹅', icon: '🦢' }, ironyTags: [] },
];
