// 天赋池：grade 0灰 1蓝 2紫 3金。eff 五维增减；tags 初始语义标签；flag 初始旗标
window.BH = window.BH || {};
BH.TALENTS = [
  // ===== 金（传说，3个）=====
  { id: 'shuzhongshu', name: '山里捡的书', emoji: '📜', g: 3, desc: '封面没有字，但你总觉得它在等你。', eff: { INT: 1 }, tags: ['xiuxian'] },
  { id: 'tiangou', name: '天选之子', emoji: '🎰', g: 3, desc: '机缘是普通人的 1.8 倍。', eff: {}, tags: ['lucky'] },
  { id: 'chongsheng', name: '梦里死过一次', emoji: '🌀', g: 3, desc: '你对死亡有一种奇怪的既视感。', eff: { JOY: -1, INT: 2 }, tags: ['weird'] },
  // ===== 紫（史诗，10个）=====
  { id: 'yeli', name: '夜里精神', emoji: '🦉', g: 2, desc: '白天是电池，晚上是发动机。', eff: { INT: 1, STR: -1 } },
  { id: 'shousu', name: '手速惊人', emoji: '⌨️', g: 2, desc: 'APM 是你唯一的朋友。', eff: { INT: 1 }, tags: ['dianjing'] },
  { id: 'xueshen', name: '学神', emoji: '🧠', g: 2, desc: '考试只是你的表演环节。', eff: { INT: 3, JOY: -1 } },
  { id: 'meimao', name: '天生丽质', emoji: '✨', g: 2, desc: '世界对你有基础滤镜。', eff: { CHR: 3 }, tags: ['fame'] },
  { id: 'fengkuang', name: '家里有矿', emoji: '⛏️', g: 2, desc: '字面意义上的。', eff: { MNY: 4 }, tags: ['rich'] },
  { id: 'leguan', name: '钝感力满分', emoji: '🛡️', g: 2, desc: '别人的阴阳怪气到你这里是白噪音。', eff: { JOY: 3 } },
  { id: 'tieshen', name: '社交牛逼症', emoji: '🦧', g: 2, desc: '电梯里你能和外卖员聊成兄弟。', eff: { CHR: 1, JOY: 1 }, tags: ['social'] },
  { id: 'tiexing', name: '锦鲤本鲤', emoji: '🐟', g: 2, desc: '抽奖永远歪，但歪出一个隐藏款。', eff: { JOY: 1 }, tags: ['lucky'] },
  { id: 'tieding', name: '命很硬', emoji: '🪨', g: 2, desc: '意外事件概率降低。', eff: { STR: 2 } },
  { id: 'yiguan', name: '艺术家人格', emoji: '🎨', g: 2, desc: '你看什么都是素材。', eff: { INT: 1, MNY: -1 }, tags: ['art'] },
  // ===== 蓝（稀有，18个）=====
  { id: 'zaoba', name: '早八战神', emoji: '⏰', g: 1, desc: '迟到界没有你的名字。', eff: { STR: 1 } },
  { id: 'laodang', name: '老当益壮', emoji: '🧓', g: 1, desc: '60 岁后体质 +2。', eff: {}, tag: null, late: { age: 60, eff: { STR: 2 } } },
  { id: 'meishi', name: '美食雷达', emoji: '🍜', g: 1, desc: '三公里内最好吃的那家你闭眼能找到。', eff: { JOY: 1 } },
  { id: 'shuimo', name: '水逆免疫', emoji: '🧿', g: 1, desc: '水逆期间你反而转运。', eff: { JOY: 1 } },
  { id: 'cunqian', name: '存钱罐成精', emoji: '🐖', g: 1, desc: '钱到你手里就开始下崽。', eff: { MNY: 2 } },
  { id: 'changpao', name: '长跑好手', emoji: '🏃', g: 1, desc: '体测是你的高光时刻。', eff: { STR: 2 } },
  { id: 'haoren', name: '老好人', emoji: '😇', g: 1, desc: '你帮过的领导后来都升职了。', eff: { CHR: 1, MNY: -1 } },
  { id: 'dazhuang', name: '打字如飞', emoji: '💬', g: 1, desc: '群聊里你的手速就是嘴替。', eff: { INT: 1 } },
  { id: 'xiuxian', name: '佛系青年', emoji: '🧘', g: 1, desc: '快乐很难掉。', eff: { JOY: 2, MNY: -1 } },
  { id: 'jixie', name: '机械键盘手', emoji: '🎹', g: 1, desc: '你会乐器的概率 +∞。', eff: { CHR: 1 } },
  { id: 'haoyun', name: '好运体质', emoji: '🍀', g: 1, desc: '抽奖小保底不歪。', eff: { JOY: 1 } },
  { id: 'meishi2', name: '干饭人', emoji: '🍚', g: 1, desc: '体质和快乐一起涨。', eff: { STR: 1, JOY: 1 } },
  { id: 'chunai', name: '纯爱战士', emoji: '💘', g: 1, desc: '恋爱事件格外青睐你。', eff: { JOY: 1 }, tags: ['love'] },
  { id: 'dushu', name: '书香门第', emoji: '📚', g: 1, desc: '家教好是刻在户口本上的。', eff: { INT: 2 }, flag: 'family_edu' },
  { id: 'gaojia', name: '书香门第·高配', emoji: '🏛️', g: 2, desc: '家教好且真有钱。', eff: { INT: 2, MNY: 2 }, flag: 'family_edu' },
  { id: 'yunde', name: '运动细胞', emoji: '⛹️', g: 1, desc: '体育老师最爱你的课代表。', eff: { STR: 2 } },
  { id: 'zhutou', name: '猪突猛进', emoji: '🐗', g: 1, desc: '先冲了再说。', eff: { STR: 1, INT: -1 } },
  { id: 'naichi', name: '耐茬', emoji: '🧱', g: 1, desc: '抗压能力超出常人。', eff: { STR: 1, JOY: 1 } },
  // ===== 灰（普通/负面，20个）=====
  { id: 'putong', name: '平平无奇', emoji: '😐', g: 0, desc: '抽到你说明这把很真实。', eff: {} },
  { id: 'yisui', name: '易碎体质', emoji: '🥀', g: 0, desc: '体质 -2，但摔得很有节目效果。', eff: { STR: -2 } },
  { id: 'shekong', name: '社恐晚期', emoji: '🫣', g: 0, desc: '社交事件会绕着你走（有时是好事）。', eff: { CHR: -1, INT: 1 } },
  { id: 'tanwan', name: '贪玩', emoji: '🎮', g: 0, desc: '快乐 +2，其他都要让路。', eff: { JOY: 2, INT: -1 } },
  { id: 'tanlan', name: '贪婪', emoji: '🤑', g: 0, desc: '家境 +3？点开看看。', eff: { MNY: -3, INT: -2 }, trap: true },
  { id: 'fenbi', name: '粉丝体质', emoji: '🎧', g: 0, desc: '追星十级学者，倒贴那种。', eff: { MNY: -1, JOY: 1 }, tags: ['fame'] },
  { id: 'aiche', name: ' emo 挂件', emoji: '🌧️', g: 0, desc: '快乐 -2，但文艺值 +1。', eff: { JOY: -2, INT: 1 }, tags: ['emo'] },
  { id: 'yueguang', name: '月光族', emoji: '🌗', g: 0, desc: '工资是过路财神。', eff: { MNY: -2 } },
  { id: 'shechi', name: '精致穷', emoji: '🥐', g: 0, desc: '钱花在哪了不知道，反正花了。', eff: { MNY: -2, CHR: 1 } },
  { id: 'shejing', name: '社精晚期', emoji: '🥴', g: 0, desc: '社交场合你是人形立牌。', eff: { CHR: -2 } },
  { id: 'shimian', name: '失眠大师', emoji: '🌙', g: 0, desc: '夜里清醒得像另一个物种。', eff: { STR: -1, INT: 1 } },
  { id: 'luanfei', name: '选择困难', emoji: '🤯', g: 0, desc: '外卖选 40 分钟的人生。', eff: { INT: -1 } },
  { id: 'zaolian', name: '早恋预备役', emoji: '💌', g: 0, desc: '情书比你先发育。', eff: { CHR: 1, INT: -1 }, tags: ['love'] },
  { id: 'laochi', name: '老吃家', emoji: '🍖', g: 0, desc: '快乐 +1 体质 -1，主打一个诚实。', eff: { JOY: 1, STR: -1 } },
  { id: 'manyu', name: '慢性子', emoji: '🐢', g: 0, desc: '急不来，真急不来。', eff: { STR: 1, INT: -1 } },
  { id: 'xiangqi', name: '想起床气', emoji: '😤', g: 0, desc: '起床是你每天的渡劫。', eff: { JOY: -1, STR: 1 } },
  { id: 'jianguo', name: '健忘', emoji: '🫥', g: 0, desc: '钥匙是你这辈子最大的敌人。', eff: { INT: -1, JOY: 1 } },
  { id: 'renqing', name: '人情通', emoji: '🧧', g: 0, desc: '份子钱永远比工资先到。', eff: { CHR: 1, MNY: -1 } },
  { id: 'zhonger', name: '中二病晚期', emoji: '🔥', g: 0, desc: '你的青春自带 BGM。', eff: { CHR: 1, INT: -1, JOY: 1 }, tags: ['chaos'] },
  { id: 'dayu', name: '大怨种', emoji: '🫏', g: 0, desc: '朋友借钱第一个想到你。', eff: { CHR: 1, MNY: -2 } },
];
