// 隐秘轨道：入口（金闪）→ 深度事件 → 独占结局
window.BH = window.BH || {};
BH.TRACKS = [
  { id: 'dianjing', name: '电竞', circle: 'dianjing', entryAge: 7,
    entryText: '🖥️【机缘】表哥带你去网吧，你打了一局……从此眼里有了光。',
    joinOpt: '记住这种感觉', passText: '你转身回家写作业，但那晚的梦全是屏幕的光。',
    passOpt: '只是玩玩',
    cond: null,
    events: [
      { id: 'de1', tr: { id: 'dianjing', d: 2 }, a: [12, 30], g: 2, t: '你在市级线下赛拿了亚军，奖金六百，奖杯是亚克力的，你擦了三年。', e: { JOY: 2, MNY: 1 }, tags: ['dianjing'] },
      { id: 'de2', tr: { id: 'dianjing', d: 3 }, inc: { trd: [['dianjing', 2]] }, a: [14, 32], g: 2, t: '你冲进了天梯前十，收到三个战队的私信，你妈以为是诈骗。', e: { CHR: 1, JOY: 1 }, tags: ['dianjing'] },
      { id: 'de3', tr: { id: 'dianjing', d: 4 }, inc: { trd: [['dianjing', 3]] }, a: [16, 36], g: 2, t: '你成了职业替补，坐了半赛季板凳，但训练赛的每一秒你都没浪费。', e: { STR: -1, JOY: 1 }, tags: ['dianjing'] },
      { id: 'de4', tr: { id: 'dianjing', d: 5 }, inc: { trd: [['dianjing', 4]] }, a: [17, 40], g: 3, t: '你终于上场了，37 秒，一个大龙，全网玩梗"37 秒传说"。', e: { CHR: 2, JOY: 2 }, tags: ['dianjing', 'fame'] },
      { id: 'dex1', tr: { id: 'dianjing', d: 6 }, inc: { trd: [['dianjing', 5]] }, a: [19, 44], g: 3, t: '世界赛决赛，决胜团，你的手指在颤抖，然后全场安静了半秒——你们赢了。', e: { CHR: 3, JOY: 3 }, tags: ['dianjing', 'fame'] },
      { id: 'dex2', tr: { id: 'dianjing', d: 6 }, inc: { trd: [['dianjing', 5]], tg: ['broke'] }, a: [19, 44], g: 3, t: '战队解散了，欠薪三个月，你抱着键盘走出基地，天特别冷。', e: { MNY: -2, JOY: -2 }, tags: ['dianjing', 'chaos'] },
    ],
    endingGood: { cond: d => d >= 6, title: '世界冠军', text: '🏆 你的ID被刻进了奖杯，解说喊你的名字喊劈了叉。' },
    endingBad: { cond: d => d >= 3, title: '退役主播', text: '🎥 你开了直播间，标题是"前职业选手，在线挨骂"。' } },
  { id: 'xiuxian', name: '修仙', circle: 'xiuxian', entryAge: 14,
    entryText: '📜【机缘】你在山里迷路，一位采药老人塞给你一本没封皮的书："有缘人，拿去。"',
    joinOpt: '翻开第一页', passText: '你把书放回了石头上，走出两步又回头看了一眼。',
    passOpt: '凡人一个，告辞',
    cond: S => (S.dims.STR >= 5 || S.talents.includes('shuzhongshu')),
    events: [
      { id: 'xx1', tr: { id: 'xiuxian', d: 2 }, inc: { trd: [['xiuxian', 1]] }, a: [14, 60], g: 2, t: '你按书上的图打了三个月坐，某天凌晨，你感觉掌心有一点微热——不是错觉。', e: { STR: 1, JOY: 1 }, tags: ['xiuxian'] },
      { id: 'xx2', tr: { id: 'xiuxian', d: 3 }, inc: { trd: [['xiuxian', 2]] }, a: [16, 70], g: 2, t: '你辟谷了七天，饿得眼冒金星，但那颗"气感"真的成了。', e: { STR: 1 }, tags: ['xiuxian'] },
      { id: 'xx3', tr: { id: 'xiuxian', d: 4 }, inc: { trd: [['xiuxian', 3]] }, a: [18, 80], g: 3, t: '你在公园晨练时被一位老爷子搭话，他称你"同门"，并请你喝了两块五一瓶的矿泉水。', e: { CHR: 1, JOY: 1 }, tags: ['xiuxian'] },
      { id: 'xx4', tr: { id: 'xiuxian', d: 5 }, inc: { trd: [['xiuxian', 4]] }, a: [20, 90], g: 3, t: '你渡劫那天雷声大作，邻居在业主群发"谁家装修"，你在阳台上盘着，笑而不语。', e: { STR: 2, CHR: 1 }, tags: ['xiuxian', 'weird'] },
      { id: 'xx5', tr: { id: 'xiuxian', d: 6 }, inc: { trd: [['xiuxian', 5]] }, a: [25, 120], g: 3, t: '百年一遇的灵气潮汐那天，你闭关了七日，出关时你的白发黑了一半。', e: { STR: 3, LIF: 20 }, tags: ['xiuxian'] },
      { id: 'xx6', tr: { id: 'xiuxian', d: 6 }, inc: { trd: [['xiuxian', 5]], dimMax: { STR: 4 } }, a: [20, 90], g: 3, t: '你强行冲关，走火入魔，在医院醒来时你对天花板说"道不同"。', e: { STR: -2, JOY: -2 }, tags: ['xiuxian', 'chaos'] },
    ],
    endingGood: { cond: d => d >= 6, title: '白日飞升', text: '🕊️ 五百岁那年你白日飞升，物业在你家门上贴了三张催缴单。' },
    endingBad: { cond: d => d >= 3, title: '红尘炼心', text: '🧘 你修了个寂寞，但学会了好心态，也算一种长生。' } },
  { id: 'fuhao', name: '富豪', circle: 'rich', entryAge: 20,
    entryText: '💰【机缘】你在旧物市场花十块钱买的一个碗，鉴定结果是——民国的。',
    joinOpt: '攥紧碗，研究搞钱', passText: '你把碗转手卖了八千，觉得自己不是搞钱的料，去吃了顿好的。',
    passOpt: '见好就收',
    cond: S => (S.dims.MNY >= 6 || S.stats.golden >= 1),
    events: [
      { id: 'fh1', tr: { id: 'fuhao', d: 2 }, inc: { trd: [['fuhao', 1]] }, a: [20, 70], g: 2, t: '你的第一桶金到账了，你把钱分成了三份：理财、存款、和一份"手滑基金"。', e: { MNY: 2, JOY: 1 }, tags: ['rich'] },
      { id: 'fh2', tr: { id: 'fuhao', d: 3 }, inc: { trd: [['fuhao', 2]] }, a: [22, 75], g: 2, t: '你全款买了房，中介鞠躬的角度让你明白了什么叫服务。', e: { MNY: 1, JOY: 1 }, tags: ['rich'] },
      { id: 'fh3', tr: { id: 'fuhao', d: 4 }, inc: { trd: [['fuhao', 3]] }, a: [24, 80], g: 3, t: '你的公司拿到了融资，签约那天你穿了一件一百二的衬衫，没人看出来。', e: { MNY: 3, CHR: 1 }, tags: ['rich'] },
      { id: 'fh4', tr: { id: 'fuhao', d: 5 }, inc: { trd: [['fuhao', 4]] }, a: [26, 85], g: 3, t: '你上了财富榜的"新锐名单"，你妈把那页报纸剪下来贴在了冰箱上。', e: { CHR: 2, JOY: 1 }, tags: ['rich', 'fame'] },
      { id: 'fh5', tr: { id: 'fuhao', d: 6 }, inc: { trd: [['fuhao', 5]] }, a: [28, 90], g: 3, t: '你的项目上市了，敲钟那一刻你想起了十块钱的那个碗。', e: { MNY: 5, CHR: 2, JOY: 2 }, tags: ['rich', 'fame'] },
      { id: 'fh6', tr: { id: 'fuhao', d: 6 }, inc: { trd: [['fuhao', 5]], f: ['allin'] }, a: [24, 85], g: 3, t: '你梭哈的那个"项目"跑路了，K 线归零，你在天台吹了很久的风，最后决定先吃碗面。', e: { MNY: -6, JOY: -3 }, tags: ['rich', 'chaos', 'broke'] },
    ],
    endingGood: { cond: d => d >= 6, title: '泼天富贵', text: '👑 你接住了泼天的富贵，也给楼下保安涨了工资。' },
    endingBad: { cond: d => d >= 3, title: '财富过山车', text: '🎢 富过，穷过，你比大多数人都懂 K 线和人心。' } },
  { id: 'hegang', name: '鹤岗', circle: 'lie', entryAge: 22,
    entryText: '🏚️【机缘】深夜刷到一条视频：《五万块，在鹤岗全款拿下一套房》。你盯着看了很久。',
    joinOpt: '研究一下路线', passText: '你关掉了视频，但"全款拿下"四个字在你心里住下了。',
    passOpt: '再想想',
    cond: S => (S.flags.includes('debt_chain') || S.dims.MNY <= 2 || S.tags.lie),
    events: [
      { id: 'hg1', tr: { id: 'hegang', d: 2 }, inc: { trd: [['hegang', 1]] }, a: [22, 70], g: 2, t: '你做好了攻略：鹤岗、乳山、个旧，三线对比表做了十八页。', e: { INT: 1, JOY: 1 }, tags: ['lie'] },
      { id: 'hg2', tr: { id: 'hegang', d: 3 }, inc: { trd: [['hegang', 2]] }, a: [23, 75], g: 2, t: '你请了年假去实地看房，中介说"这价格不是标的错，是市场的诚意"。', e: { JOY: 1, MNY: -1 }, tags: ['lie'] },
      { id: 'hg3', tr: { id: 'hegang', d: 4 }, inc: { trd: [['hegang', 3]] }, a: [24, 80], g: 2, t: '你退了城市的房子，拉着一车行李北上了，高铁上你睡得特别香。', e: { MNY: 1, JOY: 2 }, tags: ['lie'] },
      { id: 'hg4', tr: { id: 'hegang', d: 5 }, inc: { trd: [['hegang', 4]] }, a: [25, 85], g: 3, t: '你全款拿下了，八十九平，客厅大到能跑圈，你在空客厅里躺了一下午。', e: { MNY: -1, JOY: 3 }, tags: ['lie'] },
      { id: 'hg5', tr: { id: 'hegang', d: 6 }, inc: { trd: [['hegang', 5]] }, a: [26, 90], g: 3, t: '你的"鹤岗生活"系列视频火了，评论区最热的是："卷不动了，求攻略。"', e: { CHR: 2, JOY: 2 }, tags: ['lie', 'fame'] },
      { id: 'hg6', tr: { id: 'hegang', d: 6 }, inc: { trd: [['hegang', 5]], dim: { INT: 12 } }, a: [25, 85], g: 3, t: '你在家接远程单，收入比城里还高，邻居以为你是"搞互联网的"，你说对，搞命的。', e: { MNY: 3, JOY: 2 }, tags: ['lie', 'rich'] },
    ],
    endingGood: { cond: d => d >= 6, title: '反向卷王', text: '🏠 你在鹤岗活成了标杆：全款房、暖气、睡到自然醒。' },
    endingBad: { cond: d => d >= 3, title: '逃离成功', text: '🚄 你没大富大贵，但你赢了：赢在起床不闹钟。' } },
  { id: 'ouxiang', name: '偶像', circle: 'fame', entryAge: 13,
    entryText: '🎤【机缘】你在商场门口被三个举着相机的姐姐围住："妹妹/弟弟，考虑过当练习生吗？"',
    joinOpt: '接下名片', passText: '你摆摆手跑了，姐姐们在背后喊："有联系方式吗！"你跑得更快了。',
    passOpt: '跑！',
    cond: S => (S.dims.CHR >= 8 || S.talents.includes('meimao')),
    events: [
      { id: 'ox1', tr: { id: 'ouxiang', d: 2 }, inc: { trd: [['ouxiang', 1]] }, a: [13, 32], g: 2, t: '你通过了练习生面试，从此你的舞蹈房没有周末。', e: { STR: 1, CHR: 1 }, tags: ['fame'] },
      { id: 'ox2', tr: { id: 'ouxiang', d: 3 }, inc: { trd: [['ouxiang', 2]] }, a: [15, 34], g: 2, t: '你第一次公演，台下一百零三个观众，你数得清清楚楚，谢幕时手心全是汗。', e: { CHR: 1, JOY: 1 }, tags: ['fame'] },
      { id: 'ox3', tr: { id: 'ouxiang', d: 4 }, inc: { trd: [['ouxiang', 3]] }, a: [16, 36], g: 2, t: '你的直拍被剪上了热榜，一夜之间你的名字有了超话。', e: { CHR: 2, JOY: 1 }, tags: ['fame'] },
      { id: 'ox4', tr: { id: 'ouxiang', d: 5 }, inc: { trd: [['ouxiang', 4]] }, a: [17, 40], g: 3, t: '你出道了，成团位最后一个，但你站位最稳，粉丝说"稳到让人心疼"。', e: { CHR: 2, JOY: 2 }, tags: ['fame'] },
      { id: 'ox5', tr: { id: 'ouxiang', d: 6 }, inc: { trd: [['ouxiang', 5]] }, a: [18, 44], g: 3, t: '你拿了年度新人奖，获奖感言你练了二十遍，台上说的是第一遍。', e: { CHR: 3, JOY: 2 }, tags: ['fame'] },
      { id: 'ox6', tr: { id: 'ouxiang', d: 6 }, inc: { trd: [['ouxiang', 5]], tg: ['chaos'] }, a: [18, 44], g: 3, t: '你的队友塌房了，团没了，你的超话变成了考古现场。', e: { CHR: -1, JOY: -2 }, tags: ['fame', 'chaos'] },
    ],
    endingGood: { cond: d => d >= 6, title: '长红天后', text: '🌟 你红到了第七年，粉丝的平均年龄和你一起变老。' },
    endingBad: { cond: d => d >= 3, title: '意难平', text: '📼 你没红透，但你的直拍至今还在考古区流传。' } },
  { id: 'guaitan', name: '规则怪谈', circle: 'guaitan', entryAge: 16,
    entryText: '🏨【机缘】你入职第一天，前台塞给你一张纸：《员工守则》。第七条被红笔划掉了。',
    joinOpt: '开始阅读', passText: '你把守则还了回去，前台看你的眼神像在看一个逃过一劫的人。',
    passOpt: '我不干了（摔门）',
    cond: S => (S.tags.weird || S.age >= 18),
    events: [
      { id: 'gt1', tr: { id: 'guaitan', d: 2 }, inc: { trd: [['guaitan', 1]] }, a: [16, 70], g: 2, t: '守则第三条说"下班后不要回头"，你遵守了，身后传来脚步声，一直跟到地铁口就停了。', e: { JOY: -1, INT: 1 }, tags: ['guaitan', 'weird'] },
      { id: 'gt2', tr: { id: 'guaitan', d: 3 }, inc: { trd: [['guaitan', 2]] }, a: [17, 72], g: 2, t: '你发现守则第九条和第十二条是矛盾的。你把它抄在了笔记本上，旁边画了个问号。', e: { INT: 2 }, tags: ['guaitan', 'weird'] },
      { id: 'gt3', tr: { id: 'guaitan', d: 4 }, inc: { trd: [['guaitan', 3]] }, a: [18, 75], g: 3, t: '凌晨的电梯停在了不存在的十三层，门开了，外面贴着一张新告示："欢迎回来。"', e: { INT: 1, JOY: -2 }, tags: ['guaitan', 'weird'] },
      { id: 'gt4', tr: { id: 'guaitan', d: 5 }, inc: { trd: [['guaitan', 4]] }, a: [18, 80], g: 3, t: '你推理出了"冒充者"的识别方法，全公司只有你和保洁阿姨是对的，她冲你点了点头。', e: { INT: 2, CHR: 1 }, tags: ['guaitan'] },
      { id: 'gt5', tr: { id: 'guaitan', d: 6 }, inc: { trd: [['guaitan', 5]] }, a: [19, 85], g: 3, t: '你把所有规则串成了一句话，写下来贴在了前台——第二天，整栋楼的灯都没再闪过。', e: { INT: 3, CHR: 2 }, tags: ['guaitan'] },
      { id: 'gt6', tr: { id: 'guaitan', d: 6 }, inc: { trd: [['guaitan', 5]], dimMax: { INT: 6 } }, a: [19, 85], g: 3, t: '你违反了第七条。第二天，同事说你昨天请了假。可你明明记得……你摸了摸自己的工牌，照片上的人不是你。', e: { JOY: -3, INT: 1 }, tags: ['guaitan', 'weird', 'chaos'] },
    ],
    endingGood: { cond: d => d >= 6, title: '破局者', text: '🧩 你是第一个活着读完所有规则的人，新守则的最后一行写着你的名字。' },
    endingBad: { cond: d => d >= 3, title: '规则的一部分', text: '🏨 有新员工说，走廊尽头好像有个影子会帮人捡工牌。' } },
];
