// 特质池（Vampire Survivors 式三选一，全被动）
window.BH = window.BH || {};
BH.TRAITS = [
  { id: 'yinyang', name: '阴阳怪气', emoji: '🐍', d: '社交事件分支+，面试大劫有奇效', e: { CHR: 1 }, tg: ['social'], syn: { with: ['zaoba'], text: '你的阴阳怪气进化成了"早八嘴替"' } },
  { id: 'zaoba2', name: '早八课代表', emoji: '⏰', d: '迟到事件免疫，体质微涨', e: { STR: 1 }, tg: ['study'] },
  { id: 'huabing', name: '画大饼', emoji: '🫓', d: '职场事件权重+，35 岁有惊喜（惊吓）', e: {}, tg: ['social'] },
  { id: 'jingshen', name: '精神攻击免疫', emoji: '🛡️', d: 'emo 事件伤害减半', e: { JOY: 1 }, tg: ['emo'] },
  { id: 'ganfan', name: '干饭之魂', emoji: '🍚', d: '快乐+体质双修', e: { JOY: 1, STR: 1 } },
  { id: 'moyu', name: '带薪摸鱼', emoji: '🐟', d: '上班事件的快乐损耗减半', e: { JOY: 1 } },
  { id: 'shoujin', name: '攒钱的手', emoji: '🐖', d: '钱的事件增益 +1', e: { MNY: 1 } },
  { id: 'shengqian', name: '省钱大师', emoji: '🧾', d: '消费事件伤害 -1', e: { MNY: 1 }, syn: { with: ['shoujin'], text: '你的存钱罐进化成了小金库' } },
  { id: 'pao', name: '跑步机上的仙人', emoji: '🏃', d: '健康危机概率降低', e: { STR: 1 } },
  { id: 'shuimian', name: '睡眠自由', emoji: '😴', d: '熬夜事件伤害减半', e: { STR: 1, JOY: 1 } },
  { id: 'shequn', name: '群聊嘴替', emoji: '💬', d: '偶发"金句"事件', e: { CHR: 1 }, tg: ['social'] },
  { id: 'ouhuang', name: '欧皇附体', emoji: '🍀', d: '机缘概率上升', e: { JOY: 1 }, tg: ['lucky'] },
  { id: 'feiqiu', name: '非酋酋长', emoji: '🕯️', d: '机缘概率下降，但悲伤的事件会绕路（玄学）', e: { JOY: 1 } },
  { id: 'lianai', name: '恋爱脑buff', emoji: '💘', d: '恋爱事件增益翻倍（伤害也是）', e: { CHR: 1 }, tg: ['love'] },
  { id: 'duliu', name: '独狼气质', emoji: '🐺', d: '社交事件减少，专注事件增加', e: { INT: 1 }, tg: ['study'] },
  { id: 'zhonger2', name: '中二魂不灭', emoji: '🔥', d: '离谱事件概率+，人生更有节目效果', e: { JOY: 1 }, tg: ['chaos'] },
  { id: 'foxi2', name: '佛系光环', emoji: '🧘', d: '危机的负面效果减轻', e: { JOY: 1 }, tg: ['lie'] },
  { id: 'chi', name: '美食雷达', emoji: '🍜', d: '干饭快乐+1，体重的阴影+1', e: { JOY: 1 } },
  { id: 'yishu', name: '艺术家之眼', emoji: '🎨', d: '看见什么都是素材', e: { CHR: 1 }, tg: ['art'], syn: { with: ['shequn'], text: '你的朋友圈开始有人催更' } },
  { id: 'jianmei', name: '减肥失败学家', emoji: '🍰', d: '接受自己，快乐+2', e: { JOY: 2 } },
  { id: 'wanneng', name: '万金油', emoji: '🧰', d: '全维度微调，无一精通', e: { CHR: 0, INT: 0, STR: 0, MNY: 0, JOY: 0 }, tg: ['social'] },
  { id: 'yuanjia', name: '冤种 leader', emoji: '🫏', d: '同事事件Happy+，钱包-', e: { CHR: 1, MNY: -1 }, tg: ['social'] },
  { id: 'zaoqi', name: '早起星人', emoji: '🌅', d: '晨型人，健康事件增益+', e: { STR: 1 } },
  { id: 'yegui', name: '夜猫子本体', emoji: '🌙', d: '夜晚事件+，白天报废', e: { INT: 1, STR: -1 }, syn: { with: ['yinyang'], text: '你成了深夜emo区的话事人' } },
  { id: 'shouc', name: '社恐护盾', emoji: '🫣', d: '社死事件伤害减半', e: { JOY: 1 } },
  { id: 'kaogong', name: '考公体质', emoji: '📚', d: '上岸事件的判定+1', e: { INT: 1 }, tg: ['study'] },
];
