/* 梗词库
 * 正典：docs/content/lexicon.md
 * 每条词都带受众、过期风险、替换开关与复核状态；事件机制不得依赖词条。
 */
(function (g) {
  g.BH.define.lexicon([
    { id: 'lx_pofang', term: '破防', scope: 'common', risk: 'low',
      hotness: 'settled', slot: ['text', 'option', 'review', 'castname'],
      usage: '形容被戳到痛处后的失态', audience: '全体玩家', expiryRisk: 'low',
      replaceable: true, reviewStatus: 'confirmed', note: '已沉淀进日常汉语' },
    { id: 'lx_dayuanzhong', term: '大冤种', scope: 'common', risk: 'low',
      hotness: 'settled', slot: ['text', 'option', 'review', 'castname'],
      usage: '吃了亏还没处说的人', audience: '全体玩家', expiryRisk: 'low',
      replaceable: true, reviewStatus: 'confirmed', note: '已沉淀进日常汉语' },
    { id: 'lx_chouxiang', term: '抽象', scope: 'common', risk: 'low',
      hotness: 'settled', slot: ['text', 'option', 'review', 'castname'],
      usage: '失控而难以名状的表达', audience: '全体玩家', expiryRisk: 'low',
      replaceable: true, reviewStatus: 'confirmed', note: '已沉淀进日常汉语' },
    { id: 'lx_qiepian', term: '切片', scope: 'common', risk: 'low',
      hotness: 'settled', slot: ['text', 'option', 'review'],
      usage: '直播被截取传播的片段', audience: '全体玩家', expiryRisk: 'low',
      replaceable: true, reviewStatus: 'confirmed', note: '' },
    { id: 'lx_tafang', term: '塌房', scope: 'common', risk: 'low',
      hotness: 'settled', slot: ['text', 'option', 'review'],
      usage: '形象崩塌', audience: '全体玩家', expiryRisk: 'low',
      replaceable: true, reviewStatus: 'confirmed', note: '' },
    { id: 'lx_chuquan', term: '出圈', scope: 'common', risk: 'low',
      hotness: 'settled', slot: ['text', 'option', 'review'],
      usage: '传播突破原有圈层', audience: '全体玩家', expiryRisk: 'low',
      replaceable: true, reviewStatus: 'confirmed', note: '' },
    { id: 'lx_fanche', term: '翻车', scope: 'common', risk: 'low',
      hotness: 'settled', slot: ['text', 'option', 'review'],
      usage: '事情办崩', audience: '全体玩家', expiryRisk: 'low',
      replaceable: true, reviewStatus: 'confirmed', note: '' },
    { id: 'lx_shangan', term: '上岸', scope: 'common', risk: 'low',
      hotness: 'settled', slot: ['text', 'option', 'review'],
      usage: '考试或求职成功', audience: '全体玩家', expiryRisk: 'low',
      replaceable: true, reviewStatus: 'confirmed', note: '' },

    { id: 'lx_shushuwoa', term: '鼠鼠我啊', scope: 'shushu', risk: 'mid',
      hotness: 'settled', slot: ['text', 'option'],
      usage: '自嘲式的第一人称', audience: '鼠鼠/低欲望语境', expiryRisk: 'mid',
      replaceable: true, reviewStatus: 'confirmed', note: '自嘲、不怨恨' },
    { id: 'lx_xiashuidao', term: '下水道', scope: 'shushu', risk: 'mid',
      hotness: 'settled', slot: ['text'],
      usage: '自嘲所处的位置', audience: '鼠鼠/低欲望语境', expiryRisk: 'mid',
      replaceable: true, reviewStatus: 'confirmed', note: '' },

    // 以下是候选槽位：没有经过圈层复核，不应直接写入机制名或核心文本。
    { id: 'lx_guake', term: '挂科', scope: 'campus', risk: 'mid',
      hotness: '待核', slot: ['text', 'option'], usage: '校园成绩不及格',
      audience: '校园/学生语境', expiryRisk: 'mid', replaceable: true,
      reviewStatus: 'pending', note: '待圈层复核' },
    { id: 'lx_beiguo', term: '背锅', scope: 'workplace', risk: 'mid',
      hotness: '待核', slot: ['text', 'review'], usage: '承担不属于自己的责任',
      audience: '职场语境', expiryRisk: 'mid', replaceable: true,
      reviewStatus: 'pending', note: '待圈层复核' },
    { id: 'lx_kahei', term: '开黑', scope: 'esports', risk: 'mid',
      hotness: '待核', slot: ['text', 'option'], usage: '组队进行线上对局',
      audience: '电竞/游戏语境', expiryRisk: 'mid', replaceable: true,
      reviewStatus: 'pending', note: '待圈层复核' },
    { id: 'lx_dujie', term: '渡劫', scope: 'xianxia', risk: 'mid',
      hotness: '待核', slot: ['text', 'review'], usage: '仙侠语境中的关键关口',
      audience: '仙侠/修行语境', expiryRisk: 'mid', replaceable: true,
      reviewStatus: 'pending', note: '待圈层复核' },
    { id: 'lx_lengceng', term: '冷藏层', scope: 'scifi', risk: 'mid',
      hotness: '待核', slot: ['text'], usage: '科幻设施中的低温区域',
      audience: '科幻语境', expiryRisk: 'mid', replaceable: true,
      reviewStatus: 'pending', note: '待圈层复核' },
    { id: 'lx_zoulang', term: '走廊', scope: 'lingyi', risk: 'mid',
      hotness: '待核', slot: ['text'], usage: '怪谈中反复出现的过渡空间',
      audience: '灵异/怪谈语境', expiryRisk: 'mid', replaceable: true,
      reviewStatus: 'pending', note: '待圈层复核' },
  ]);
})(typeof globalThis !== 'undefined' ? globalThis : this);
